---
- name: Install and Deploy WAR to Tomcat on Ubuntu
  hosts: tomcat_servers
  become: true
  vars:
    tomcat_service: tomcat9
    tomcat_webapps: /var/lib/tomcat9/webapps

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java (required for Tomcat)
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install Tomcat
      apt:
        name: tomcat9
        state: present

    - name: Ensure Tomcat service is running
      service:
        name: "{{ tomcat_service }}"
        state: started
        enabled: yes

    - name: Copy WAR file to Tomcat webapps
      copy:
        src: "{{ artifact }}"
        dest: "{{ tomcat_webapps }}/devops-app.war"
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Restart Tomcat
      service:
        name: "{{ tomcat_service }}"
        state: restarted

