---
- name: Install and Deploy WAR to Tomcat on Ubuntu
  hosts: localhost
  become: true
  vars:
    tomcat_service: tomcat9
    tomcat_webapps: /var/lib/tomcat9/webapps

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java (required for Tomcat)
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Download Tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.109/bin/apache-tomcat-9.0.109.tar.gz"
        dest: /opt/
    - name: Extract Tomcat
      unarchive:
        src: /opt/apache-tomcat-9.0.109.tar.gz
        dest: /opt/
        remote_src: yes
    - name: Configure Tomcat Users
      template:
        src: tomcat-users.xml
        dest: /opt/apache-tomcat-9.0.109/conf/tomcat-users.xml
    - name: Start Tomcat Service
      service:
        name: tomcat
        state: started
        enabled: yes

    - name: Copy WAR file to Tomcat webapps
      copy:
        src: "{{ artifact }}"
        dest: "{{ tomcat_webapps }}/devops-app.war"
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Restart Tomcat
      service:
        name: "{{ tomcat_service }}"
        state: restarted

