---
#- name: Deploy WAR to Tomcat on localhost
  # hosts: localhost
#  become: yes
 # vars:
  #  tomcat_service: tomcat10.1.45
   # tomcat_webapps: /var/lib/tomcat10.1.45/webapps

 # tasks:
 #   - name: Ensure Tomcat is installed
 #     apt:
 #       name: tomcat10.1.45
#        state: present
 #       update_cache: yes

  #  - name: Ensure Tomcat service is running
  #    service:
   #     name: "{{ tomcat_service }}"
  #      state: started
 #       enabled: yes#
 - name: Install Tomcat
  hosts: tomcat_servers
  become: true
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present
    - name: Download Tomcat
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz"
        dest: /opt/
    - name: Extract Tomcat
      unarchive:
        src: /opt/apache-tomcat-9.0.54.tar.gz
        dest: /opt/
        remote_src: yes
    - name: Configure Tomcat Users
      template:
        src: tomcat-users.xml.j2
        dest: /opt/apache-tomcat-9.0.54/conf/tomcat-users.xml
    - name: Start Tomcat Service
      service:
        name: tomcat
        state: started
        enabled: yes

    - name: Copy WAR file to Tomcat webapps
      copy:
        src: "{{ artifact }}"
        dest: "{{ tomcat_webapps }}/devops-app.war"
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Restart Tomcat
      service:
        name: "{{ tomcat_service }}"
        state: restarted
